@startuml

activate 客户端
note left of 客户端: 通过固定(多个)域名
客户端 -> 代理机: 访问
activate 代理机

note left of 代理机: 开发机修改后,自动同步到代理机, 支持多用户, 即根目录下支持多个项目
代理机 -> 代理机: 查找资源
代理机 -> 线上机器: 自己没有,请求资源
客户端 <-- 代理机: 资源
deactivate 代理机
@enduml