@startuml
'add title
title Simple communication example

'自动的给消息加上编号
'autonumber

A ---x B : 标识消息丢失

note left: this is a first note

'增加空间
|||
...5s后, 这里用于表示延迟...
|||

A --\ B: 一半的箭头



newpage 下一页的标题


A ---/ B: 一半的箭头
A -// B: 空心的箭头
deactivate B
A -\\ B: 空心的箭头
A -->> B: 空心箭头


newpage
'color

A -[#green]> B: use color


legend bottom
这里是备注的内容,legend
endlegend



C -> D : request
D --> C: 200
activate C
activate D
C -> D : request
D --> C: 302
deactivate C
C -> D : request
deactivate D
D --> C: 404


@enduml